-help:
	@echo ""
	@echo "Usage: make [target]"
	@echo ""
	@echo "Main build targets:"
	@echo "  $(MABOLD)all        $(R)     Build the main IRC server executable $(G)($(NAME))$(R)"
	@echo "  $(MABOLD)debug      $(R)     Build the debug IRC server executable $(G)($(DEBUG_NAME))$(R)"
	@echo "  $(MABOLD)bot        $(R)     Build the IRC bot executable $(G)($(BOT_NAME))$(R)"
	@echo "  $(MABOLD)debugbot   $(R)     Build the debug IRC bot executable $(G)($(BOT_DEBUG_NAME))$(R)"
	@echo ""
	@echo "Clean targets:"
	@echo "  $(MABOLD)clean      $(R)     Remove all build directories"
	@echo "  $(MABOLD)fclean     $(R)     Remove all build directories and all executables/logs"
	@echo "  $(MABOLD)cleanserv  $(R)     Remove server and debug server object files"
	@echo "  $(MABOLD)fcleanserv $(R)     Remove server and debug server executables and logs"
	@echo "  $(MABOLD)cleanbot   $(R)     Remove bot and debug bot object files"
	@echo "  $(MABOLD)fcleanbot  $(R)     Remove bot and debug bot executables and logs"
	@echo ""
	@echo "Rebuild targets:"
	@echo "  $(MABOLD)re         $(R)     Full clean and rebuild (all and bot)"
	@echo "  $(MABOLD)reserver   $(R)     Full clean and rebuild server"
	@echo "  $(MABOLD)rebot      $(R)     Full clean and rebuild bot"
	@echo ""
	@echo "Run targets: Default port is 6667, but you may specify 6667."
	@echo "  $(MABOLD)run        $(R)     Run the IRC server $(G)($(NAME))$(R)."
	@echo "  $(MABOLD)drun       $(R)     Run the debug IRC server $(G)($(DEBUG_NAME))$(R) with valgrind"
	@echo "  $(MABOLD)brun       $(R)     Run the IRC bot $(G)($(BOT_NAME))$(R)"
	@echo "  $(MABOLD)dbrun      $(R)     Run the debug IRC bot $(G)($(BOT_DEBUG_NAME))$(R) with valgrind"
	@echo ""
	@echo "Other targets:"
	@echo "  $(MABOLD)info       $(R)     Print build info"
	@echo "  $(MABOLD)track      $(R)     Track remote git branches"
	@echo "  $(MABOLD)format     $(R)     Format all source files"
	@echo ""
	@echo "For more information, see the Makefile source."
